# .github/workflows/build.yml
name: Build

on:
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make g++ \
            nlohmann-json3-dev \
            libcurl4-openssl-dev \
            libnotify-dev

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      # Optional: Run tests if you have them
      # - name: Run tests
      #   run: |
      #     cd build
      #     ctest --output-on-failure
